WORKOUT_EASY_OR_LONG = "easy_or_long"
WORKOUT_INTERVAL = "interval"
WORKOUT_HILL_REPEATS = "hill_repeats"

ALL_WORKOUT_TYPES = {
    WORKOUT_EASY_OR_LONG,
    WORKOUT_INTERVAL,
    WORKOUT_HILL_REPEATS,
}

STREAM_WORKOUT_TYPES = ["interval", "hill_repeats"]

WORKOUT_LABEL = "WORKOUT"
REST_LABEL = "REST"
STEADY_LABEL = "STEADY"
WARMUP_LABEL = "WARMUP"
COOLDOWN_LABEL = "COOLDOWN"

INTERVAL_WORKOUT_SCORE = 0.45
INTERVAL_REST_SCORE = -0.5

HILL_WORKOUT_SCORE = 0.5
HILL_REST_SCORE = -0.5