WORKOUT_EASY_OR_LONG = "easy_or_long"
WORKOUT_INTERVAL = "interval"
WORKOUT_HILL_REPEATS = "hill_repeats"

ALL_WORKOUT_TYPES = {
    WORKOUT_EASY_OR_LONG,
    WORKOUT_INTERVAL,
    WORKOUT_HILL_REPEATS,
}