-- CreateTable
CREATE TABLE "meals" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "type" "meal_type" NOT NULL,
    "order" INTEGER NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "meals_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "meals_user_id_order_idx" ON "meals"("user_id", "order");

-- AddForeignKey
ALTER TABLE "meals" ADD CONSTRAINT "meals_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- Data migration (hand-written, not generated by `prisma migrate`): every
-- existing user gets the five slots the UI used to render hardcoded, in
-- *display* order (SNACK before DINNER) -- which is NOT the declaration
-- order of the meal_type enum.
-- Seeded ids are uuids rather than the cuids MealsService.create writes.
-- Cosmetic only: the column is TEXT and Prisma never parses an id.
INSERT INTO "meals" ("id", "user_id", "type", "order")
SELECT gen_random_uuid()::text, u."id", d."type", d."order"
FROM "users" u
CROSS JOIN (VALUES
  ('BREAKFAST'::"meal_type", 1),
  ('LUNCH'::"meal_type",     2),
  ('SNACK'::"meal_type",     3),
  ('DINNER'::"meal_type",    4),
  ('SUPPER'::"meal_type",    5)
) AS d("type", "order");

-- AlterTable: nullable first, so the backfill below has somewhere to write
ALTER TABLE "food_logs" ADD COLUMN "meal_id" TEXT;

UPDATE "food_logs" fl
SET "meal_id" = m."id"
FROM "meals" m
WHERE m."user_id" = fl."user_id" AND m."type" = fl."meal_type";

-- The five seeded slots cover the whole enum, so every row must have matched.
-- SET NOT NULL is the guard itself: it aborts the migration transaction if any
-- row is still NULL, instead of silently losing logs.
ALTER TABLE "food_logs" ALTER COLUMN "meal_id" SET NOT NULL;

-- CreateIndex
CREATE INDEX "food_logs_meal_id_idx" ON "food_logs"("meal_id");

-- AddForeignKey: CASCADE is deliberate (deleting a meal deletes its logs on
-- every day, behind an explicit confirmation in the UI). This is the OPPOSITE
-- of the SET NULL chosen for workouts.template_id.
ALTER TABLE "food_logs" ADD CONSTRAINT "food_logs_meal_id_fkey" FOREIGN KEY ("meal_id") REFERENCES "meals"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AlterTable: drops the *column*; the "meal_type" enum type stays, meals.type uses it
ALTER TABLE "food_logs" DROP COLUMN "meal_type";
